MODEL:
  WEIGHT: 'MODEL/glip_tiny_model_o365_goldg_cc_sbu.pth'
  LANGUAGE_BACKBONE:
    MAX_QUERY_LEN: 310
    FREEZE: True
  BACKBONE:
    FREEZE_CONV_BODY_AT: -1
    FREEZE: True
  FPN:
    FREEZE: True
  RPN:
    FREEZE: False
  ATSS:
    DETECTIONS_PER_IMG: 36
    NMS_TH: 0.5
  DYHEAD:
    NUM_CLASSES: 151
    SCORE_AGG: "MEAN"
    RELATION_CONSISTENCY_ON: True
    RELATION_REP_REFINER: False
  ROI_RELATION_HEAD:
    PREDICT_USE_BIAS: True

DATASETS:
  TRAIN: ('vg150_train',)
  TEST: ('vg150_test',)
  DISABLE_SHUFFLE: True
  VG150_SPLIT_KEY: 'split_GLIPunseen'

# training
SOLVER:
  MAX_EPOCH: 6
  CHECKPOINT_PERIOD: 5000
  FIND_UNUSED_PARAMETERS: False
  BASE_LR: 0.000005
  LANG_LR: 0.00001
  STEPS: (0.6, 0.8)
  IMS_PER_BATCH: 1
  TEST_WITH_INFERENCE: True
  USE_AMP: True
AUGMENT:
  FLIP_PROB_TRAIN: 0.0

# testing
TEST:
  EVAL_TASK: detection
  DURING_TRAINING: True
  IMS_PER_BATCH: 1

OUTPUT_DIR: 'OUTPUT/xxx'
